version: '3.5'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: pxdmail-codeception-example
    image: pxdmail-codeception-example:pxdmail-codeception-example
    container_name: pxdmail-codeception-example
    hostname: docker-dev-local-om3
    ports:
      - "1025:80"
    volumes:
      - .:/app
